//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"bytes"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"text/template"
)

const (
	sourceFile     = "header.txt"
	resultFile     = "header_constants.go"
	resultTemplate = `// НЕ РЕДАКТИРОВАТЬ! Изменения будут перезаписаны при следующей кодогенерации.
// Code generated by go generate; DO NOT EDIT.

package dic

// Headers Структура справочника заголовков.
type Headers struct {
{{- range .}}
	// {{.Name}} Заголовок "{{.Source}}", {{.Description}}
	{{.Name}}	IHeader
{{- end}}
}

func init() {
	singletonHeader = Headers{
{{- range .}}
		{{.Name}}: &tHeader{header: "{{.Source}}"},
{{- end}}
	}
}
`
)

type source struct {
	Name        string
	Source      string
	Description string
}

func main() {
	var (
		err    error
		src    []*source
		result *bytes.Buffer
		tpl    *template.Template
		data   []byte
	)

	if src, err = readSource(sourceFile); err != nil {
		log.Fatalf("чтение файла %q прервано ошибкой: %s", sourceFile, err)
		return
	}
	sort.SliceStable(src, func(i, j int) bool { return strings.Compare(src[i].Name, src[j].Name) == -1 })
	result = &bytes.Buffer{}
	tpl = template.Must(template.New(resultFile).Parse(resultTemplate))
	if err = tpl.Execute(result, src); err != nil {
		log.Fatalf("шаблонизатор завершился с ошибкой: %s", err)
		return
	}
	if data, err = format.Source(result.Bytes()); err != nil {
		log.Fatalf("форматирование созданного .go файла прервано ошибкой: %s", err)
		return
	}
	if err = os.WriteFile(resultFile, data, os.FileMode(0644)); err != nil {
		log.Fatalf("создание файла %q прервано ошибкой: %s", resultFile, err)
		return
	}
}

func readSource(f string) (ret []*source, err error) {
	const sep = "|"
	var (
		data    []byte
		scanner *bufio.Scanner
		line    []string
	)

	if data, err = os.ReadFile(f); err != nil {
		return
	}
	scanner = bufio.NewScanner(bytes.NewBuffer(data))
	for scanner.Scan() {
		if line = strings.Split(scanner.Text(), sep); len(line) != 3 {
			continue
		}
		ret = append(ret, &source{
			Name:        strings.TrimSpace(line[0]),
			Source:      strings.TrimSpace(line[1]),
			Description: strings.TrimSpace(line[2]),
		})
	}

	return
}
